baseURL = "http://options.cafe/"
languageCode = "en-us"
title = "Options Cafe"

[params]
  description = "Options Cafe decided has taken an entirely different approach: to excel at options only. Our options trading software provides best way to trade options."
