baseURL = 'https://options.cafe/'
languageCode = 'en-us'
title = 'Options Cafe'
publishDir = "docs"
paginate = 10
disableHugoGeneratorInject = true

[taxonomies]
  blog_tag = "blog_tags"
  category = "categories"
  help_category = "help_categories"

[permalinks]
  blog_tags = "/related-topics/:slug/"
  categories = "/blog/:slug/"

[params]
    copyRightYear = 2023
    newsletterHeader = false
    defaultShareImage = 'blog/options-cafe-cover.png'
    appLogin = 'https://app.options.cafe/login'
    twitterHandle = 'options_cafe'
    defaultTitle = 'Helping You Succeed With Options Trading!'
    defaultDescription = 'Options Cafe is a free options screener and trading platform. We provide a free options screener, a free options trading platform, and a free options trading community.'
    twitterLink = 'https://twitter.com/options_cafe'
    facebookAppId = '1512164148794908'
    facebookPageId = '730529083708603'
    facebookLink = 'https://www.facebook.com/optionscafetrading'
    appSignUpLink = 'https://app.options.cafe/register'
    helpCategories = ['Getting Started', 'Broker Support', 'Options Screener']
    blogCategories = ['Education', 'Random Fun', "Spicer's Trades", "Spicer's Soapbox", 'Company Updates']