version: '2.1'

services:

  # App
  web:

    hostname: ${VIRTUAL_HOST}

    container_name: ${VIRTUAL_HOST}

    build:
      context: ./build
      dockerfile: Dockerfile
      args:
        P_UID: ${P_UID}
        P_GID: ${P_GID}       
    
    image: ${VIRTUAL_HOST}/nginx-php70

    restart: always

    environment:   
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}      
  
    volumes:
      - ../www:/www:ro
      - ../www/storage:/www/storage:rw
      - ../www/public/cpresources:/www/public/cpresources:rw
      - ./logs:/logs:rw
      
    networks:
      - shared
  
networks:
  shared:
    external:
      name: shared         
