---

- name: Deploys the server config for options.cafe to production
  
  hosts: web-servers
  
  become: yes
  
  become_user: root

  roles:
    - bootstrap
    - users
    - docker-sites
    - docker-mysql
    - docker-nginx-proxy
    
  vars_files:
    - "vars/encrypt.yml"
    - "vars/all.yml"    
